kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example-resource-template-pvc
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
  resources:
    requests: 
      storage: 1Gi
