apiVersion: v1
kind: ConfigMap
metadata:
  name: "example-resource-template-new-dep"
  labels:
    streams-custom-resource-template: "true"
 
data:
 
 newdep.yaml: |
   apiVersion: v1
   kind: Pod
   metadata:
     annotations:
       mytest: "New dep annotation"
     labels:
       testapp: newdeplabel
   spec:
     imagePullSecrets:
       - name: <secret-name>     
     containers:
       - name: controller
         image: <new-custom-image-registry-name>/<new-custom-image-name>:<new-custom-image-tag>
         imagePullPolicy: Always
